version: 2.1

jobs:
  build:
    working_directory: ~/funky-claude
    docker:
      - image: circleci/node:10.6
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: deps-and-checkouts-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: deps-and-checkouts-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./checkouts
      - run:
          name: test helix-static
          command: npm run test-repo git@github.com:adobe/helix-static.git
          when: always
      - run:
          name: test helix-example-basic
          command: npm run test-repo git@github.com:adobe/helix-example-basic.git
          when: always
      - run:
          name: test helix-example-advanced
          command: npm run test-repo git@github.com:adobe/helix-example-advanced.git
          when: always
      - run:
          name: test helix-log
          command: npm run test-repo git@github.com:adobe/helix-log.git
          when: always
